FileVersion = 1

[Project]
Name = "dr_flac"
TargetType = "BeefLib"
StartupObject = "dr_flac.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\dr_flac_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\dr_flac.lib"]
