FileVersion = 1

[Project]
Name = "dr_flac"
TargetType = "BeefLib"
StartupObject = "dr_flac.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\dr_flacd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\dr_flac.lib"]
