FileVersion = 1

[Project]
Name = "dr_mp3"
TargetType = "BeefLib"
StartupObject = "dr_mp3.Program"


[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\dr_mp3_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\dr_mp3.lib"]