FileVersion = 1

[Project]
Name = "dr_wav"
TargetType = "BeefLib"
StartupObject = "dr_wav.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\dr_wavd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\dr_wav.lib"]
